// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGcAW4RgDnhc7ey35ArXnsRAdaKsNIfY',
    appId: '1:540730807453:web:5b0a76b2fba0d07815b074',
    messagingSenderId: '540730807453',
    projectId: 'ceyloan-360-9c242',
    authDomain: 'ceyloan-360-9c242.firebaseapp.com',
    storageBucket: 'ceyloan-360-9c242.firebasestorage.app',
    measurementId: 'G-7B6NK5WKRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMbnt0eSAv3A7up9xB2N86EqM7y0_kZM',
    appId: '1:540730807453:android:b11043212998ef4115b074',
    messagingSenderId: '540730807453',
    projectId: 'ceyloan-360-9c242',
    storageBucket: 'ceyloan-360-9c242.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-3IXhJQvZ0ZfQASGagbCU1J5b8agpBU',
    appId: '1:540730807453:ios:82536206e9601abf15b074',
    messagingSenderId: '540730807453',
    projectId: 'ceyloan-360-9c242',
    storageBucket: 'ceyloan-360-9c242.firebasestorage.app',
    androidClientId: '540730807453-bs5m44dlb6o9ptqk4qslbi55q82l0d76.apps.googleusercontent.com',
    iosClientId: '540730807453-659idtjjr2hs840cjjimttakpv408eq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceyloan360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcGcAW4RgDnhc7ey35ArXnsRAdaKsNIfY',
    appId: '1:540730807453:web:c169094b0428504215b074',
    messagingSenderId: '540730807453',
    projectId: 'ceyloan-360-9c242',
    authDomain: 'ceyloan-360-9c242.firebaseapp.com',
    storageBucket: 'ceyloan-360-9c242.firebasestorage.app',
    measurementId: 'G-8EX5XBY9V9',
  );

}